#!/usr/bin/env bash

function runcmd {
    [[ $VERBOSITY == 1 ]] && echo "$@"
    "$@"
}

# Automatically adds the interface private key from a separate file.
if [[ "$IFACE" == wg* ]]; then
    # If the interface block specifies a specific key, use that. Otherwise,
    # search standard interface-specific paths, then a system wireguard
    # default path.
    if [[ "$IF_WG_PRIVATE_KEY" ]]; then
        private_keyfile="$IF_WG_PRIVATE_KEY"
    elif [[ -f /etc/wireguard/"$IFACE".key ]]; then
        private_keyfile=/etc/wireguard/"$IFACE".key
    elif [[ -f /etc/wireguard/"$IFACE"/private.key ]]; then
        private_keyfile=/etc/wireguard/"$IFACE"/private.key
    elif [[ -f /etc/wireguard/private.key ]]; then
        private_keyfile=/etc/wireguard/private.key
    else
        echo "Error: No private key specified." >&2
        exit 1
    fi

    # Reject the key if it's accessible to anyone other than root.
    keyfile_mode=$(stat --format %a "$private_keyfile")
    if [[ $keyfile_mode != ?00 ]]; then
        printf "Error: private key '%s' mode %s, should be 600\n" \
            "$private_keyfile" $keyfile_mode >&2
        exit 1
    fi

    runcmd wg set "$IFACE" private-key "$private_keyfile"
fi
