#!/usr/bin/env bash

function runcmd {
    [[ $VERBOSITY == 1 ]] && echo "$@"
    "$@"
}

function loadconf {
    local config_path="$1"

    # Refuse to load the config if it is writable by others.
    config_mode=$(stat --format %A "$config_path")
    if [[ $config_mode != ?????-??-? ]]; then
        printf "Error: Config file '%s' is writable by others.\n" \
            "$config_path" >&2
        exit 1
    fi

    # Refuse to load the config if it overrides the private key. For security
    # reasons, private keys should be separate and have mode 600.
    if fgrep -isq 'PrivateKey' "$config_path"; then
        echo "Error: Specifying private key in config file is unsupported." >&2
        exit 1
    fi

    runcmd wg addconf "$IFACE" "$config_path"
}

# Apply any matching wireguard configs found, in order:
#     * Interface-specific config in interface-specific folder
#     * Interface-specific config in default wireguard folder
#     * Custom interface option 'wg-config-file'
if [[ "$IFACE" == wg* ]]; then
    if [[ -f /etc/wireguard/"$IFACE"/config ]]; then
        loadconf /etc/wireguard/"$IFACE"/config
    fi

    if [[ -f /etc/wireguard/"$IFACE".conf ]]; then
        loadconf /etc/wireguard/"$IFACE".conf
    fi

    if [[ -f "$IF_WG_CONFIG_FILE" ]]; then
        loadconf "$IF_WG_CONFIG_FILE"
    fi
fi
